[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd ../frontend && npm install && npm run build"

[deploy]
startCommand = "node src/index.js"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
